rule all:
    input:
        "results/use_shell.txt",
        "results/use_script.txt"

rule use_shell:
    output: "results/use_shell.txt"
    shell:
        """
        echo "$PWD"
        bin/hello > {output}
        """

rule use_script:
    output: "results/use_script.txt"
    script: "bin/hello.sh"

