module module_workflow:
    snakefile:"module/Snakefile"
    config: config
    prefix: "module"

use rule * from module_workflow as *

rule all:
    input:
        rules.module_all.input
    shell:
        """
        echo "$PWD"
        ./module/bin/hello
        """
