
EXPECTED_WORKFLOWS = ["phylogenetic", "ingest", "nextclade"]

# Conditionally import workflow module based on the config
# The default workflow is the phylogenetic workflow if no config value is provided
target_workflow = config.get("workflow", "phylogenetic").lower()

if target_workflow not in EXPECTED_WORKFLOWS:

    raise ValueError(
        f"ERROR: Config set to unknown workflow {target_workflow!r}. " +
        f"Please use one of the expected workflows: {EXPECTED_WORKFLOWS!r}"
    )


include: f"{target_workflow}/Snakefile"

rule default_target:
    input: rules.all.input
    default_target: True
