name: Notify Slack on failure
description: >-
  Sends Slack notification with link to a GitHub Action workflow run that failed.

  Intended to be used for automated pathogen build workflows to ensure that the
  entire team is notified of a GitHub Action failure and not just the GitHub
  user who originally launched and/or scheduled the workflow.

  Requires two environment variables to be set:
  - SLACK_TOKEN
  - SLACK_CHANNELS

  The SLACK_TOKEN is the OAuth token for the Slack app that has permissions to send messages.
  The SLACK_CHANNELS is the name or channel id for the intended Slack channel.

runs:
  using: composite
  steps:
  - uses: actions/checkout@v3
    with:
      repository: nextstrain/ingest
      ref: notify-slack
      path: nextstrain-ingest
      sparse-checkout: |
        notify-on-job-fail

  - name: Notify job failure
    shell: bash
    run: ./nextstrain-ingest/notify-on-job-fail "$WORKFLOW_NAME" "$JOB_REPO"
    env:
      GITHUB_RUN_ID: ${{ github.run_id }}
      WORKFLOW_NAME: ${{ github.workflow }}
      JOB_REPO: ${{ github.event.repository.name }}
