name: Notify Slack on failure
description: >-
  Sends Slack notification with link to a GitHub Action workflow run that failed.

  Intended to be used for automated pathogen build workflows to ensure that the
  entire team is notified of a GitHub Action failure and not just the GitHub
  user who originally launched and/or scheduled the workflow.

inputs:
  slack_token:
    description: >-
      OAuth token for the Slack App that has permissions to send messages.
    type: string
    required: true
  slack_channel:
    description: >-
      The name or channel id for the intended Slack channel.
    type: string
    required: true


runs:
  using: composite
  steps:
  - uses: actions/checkout@v3
    with:
      repository: nextstrain/ingest
      ref: notify-slack
      path: nextstrain-ingest
      sparse-checkout: |
        notify-on-job-fail

  - name: Notify job failure
    shell: bash
    run: ./nextstrain-ingest/notify-on-job-fail "$WORKFLOW_NAME" "$JOB_REPO"
    env:
      GITHUB_RUN_ID: ${{ github.run_id }}
      SLACK_TOKEN: ${{ inputs.slack_token }}
      SLACK_CHANNELS: ${{ inputs.slack_channel }}
      WORKFLOW_NAME: ${{ github.workflow }}
      JOB_REPO: ${{ github.event.repository.name }}
