name: Test continue-on-error

on: workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - id: sleep
        run: sleep 5m
    outputs:
      sleep-step-conclusion: ${{ steps.sleep.conclusion }}

  job2:
    runs-on: ubuntu-latest
    needs: [ job1 ]
    if: ${{ !failure() && needs.job1.outputs.sleep-step-conclusion == 'cancelled' }}
    env:
      CONCLUSION: ${{ needs.job1.outputs.sleep-step-conclusion }}
      RESULT: ${{ needs.job1.result }}
    timeout-minutes: 1
    steps:
      - id: attach
        run: |
          echo "CONCLUSION=$CONCLUSION"
          echo "RESULT=$RESULT"

      - id: sleep
        run: sleep 5m
    outputs:
      sleep-step-conclusion: ${{ steps.sleep.conclusion }}

  job3:
    runs-on: ubuntu-latest
    needs: [ job2 ]
    if: ${{ !failure() && needs.job2.outputs.sleep-step-conclusion == 'cancelled' }}
    env:
      CONCLUSION: ${{ needs.job2.outputs.sleep-step-conclusion }}
      RESULT: ${{ needs.job2.result }}
    timeout-minutes: 1
    steps:
      - id: attach
        run: |
          echo "CONCLUSION=$CONCLUSION"
          echo "RESULT=$RESULT"

      - id: sleep
        run: sleep 5m
    outputs:
      sleep-step-conclusion: ${{ steps.sleep.conclusion }}

  job4:
    runs-on: ubuntu-latest
    needs: [ job3 ]
    if: ${{ !failure() && needs.job3.outputs.sleep-step-conclusion == 'cancelled' }}
    env:
      CONCLUSION: ${{ needs.job3.outputs.sleep-step-conclusion }}
      RESULT: ${{ needs.job3.result }}
    timeout-minutes: 1
    steps:
      - id: attach
        run: |
          echo "CONCLUSION=$CONCLUSION"
          echo "RESULT=$RESULT"

      - id: sleep
        run: sleep 5m
    outputs:
      sleep-step-conclusion: ${{ steps.sleep.conclusion }}

  job5:
    runs-on: ubuntu-latest
    needs: [ job4 ]
    if: ${{ !failure() && needs.job4.outputs.sleep-step-conclusion == 'cancelled' }}
    env:
      CONCLUSION: ${{ needs.job4.outputs.sleep-step-conclusion }}
      RESULT: ${{ needs.job4.result }}
    timeout-minutes: 1
    steps:
      - id: attach
        run: |
          echo "CONCLUSION=$CONCLUSION"
          echo "RESULT=$RESULT"

      - id: sleep
        run: sleep 5m
    outputs:
      sleep-step-conclusion: ${{ steps.sleep.conclusion }}

  wait-conclusion:
    needs: [job2, job3, job4, job5]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: All attach steps in wait-N jobs were successful (or skipped)
        run: |
          # shellcheck disable=SC2242

          exit ${{ contains(needs.*.outputs.sleep-step-conclusion, 'failure') && '1' || '0' }}
