name: Test continue-on-error

on: workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - id: sleep
        run: sleep 5m
    outputs:
      sleep-step-conclusion: ${{ steps.sleep.conclusion }}

  job2:
    runs-on: ubuntu-latest
    needs: [ job1 ]
    if: ${{ always() }}
    env:
      CONCLUSION: ${{ needs.job1.outputs.sleep-step-conclusion }}
      RESULT: ${{ needs.job1.result }}
    steps:
      - id: attach
        run: |
          echo "CONCLUSION=$CONCLUSION"
          echo "RESULT=$RESULT"
    outputs:
      attach-step-conclusion: ${{ steps.attach.conclusion }}

  job3:
    runs-on: ubuntu-latest
    needs: [ job1 ]
    if: ${{ needs.job1.outputs.sleep-step-conclusion == 'cancelled' }}
    env:
      CONCLUSION: ${{ needs.job1.outputs.sleep-step-conclusion }}
      RESULT: ${{ needs.job1.result }}
    steps:
      - id: attach
        run: |
          echo "CONCLUSION=$CONCLUSION"
          echo "RESULT=$RESULT"
    outputs:
      attach-step-conclusion: ${{ steps.attach.conclusion }}

  job4:
    runs-on: ubuntu-latest
    needs: [ job1 ]
    if: ${{ !cancelled() && needs.job1.outputs.sleep-step-conclusion == 'cancelled' }}
    env:
      CONCLUSION: ${{ needs.job1.outputs.sleep-step-conclusion }}
      RESULT: ${{ needs.job1.result }}
    steps:
      - id: attach
        run: |
          echo "CONCLUSION=$CONCLUSION"
          echo "RESULT=$RESULT"
    outputs:
      attach-step-conclusion: ${{ steps.attach.conclusion }}

  job5:
    runs-on: ubuntu-latest
    needs: [ job1 ]
    if: ${{ always() && needs.job1.outputs.sleep-step-conclusion == 'cancelled' }}
    env:
      CONCLUSION: ${{ needs.job1.outputs.sleep-step-conclusion }}
      RESULT: ${{ needs.job1.result }}
    steps:
      - id: attach
        run: |
          echo "CONCLUSION=$CONCLUSION"
          echo "RESULT=$RESULT"
    outputs:
      attach-step-conclusion: ${{ steps.attach.conclusion }}

  wait-conclusion:
    needs: [job2, job3, job4, job5]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: All attach steps in wait-N jobs were successful (or skipped)
        run: |
          # shellcheck disable=SC2242

          exit ${{ contains(needs.*.outputs.attach-step-conclusion, 'failure') && '1' || '0' }}
