name: Ingest

defaults:
  run:
    # This is the same as GitHub Action's `bash` keyword as of 20 June 2023:
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell
    #
    # Completely spelling it out here so that GitHub can't change it out from under us
    # and we don't have to refer to the docs to know the expected behavior.
    shell: bash --noprofile --norc -eo pipefail {0}

on:
  schedule:
    - cron: '*/5 * * * *'

  workflow_dispatch:
    inputs:
      fail:
        description: Fail workflow if true
        type: boolean

jobs:
  ingest:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Mock ingest"
      - if: ${{ inputs.fail }}
        run: echo "Failing ingest workflow" && exit 1
