name: Job dependencies

on: workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1

  notify-failure:
    if: ${{ failure() }}
    needs: [job1]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./actions/notify-on-failure
      env:
        SLACK_TOKEN: "test-token"
        SLACK_CHANNELS: "test-channel"
