name: Phylogenetic

defaults:
  run:
    # This is the same as GitHub Action's `bash` keyword as of 20 June 2023:
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell
    #
    # Completely spelling it out here so that GitHub can't change it out from under us
    # and we don't have to refer to the docs to know the expected behavior.
    shell: bash --noprofile --norc -eo pipefail {0}

on:
  # This workflow will be triggered after the "Ingest" workflow has completed on the "main" branch.
  workflow_run:
    workflows:
      - Ingest
    types:
      - completed
    branches:
      - main

  workflow_dispatch:

jobs:
  check-new-data:
    if: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.check-cache.outputs.cache-hit }}
    steps:
      - name: Get sha256sum
        id: get-sha256sum
        run: echo $(date '+%Y-%m-%d') | tee -a ingest-output-sha256sum

      - name: Check cache
        id: check-cache
        uses: actions/cache@v4
        with:
          path: ingest-output-sha256sum
          key: ingest-output-sha256sum-${{ hashFiles('ingest-output-sha256sum') }}
          lookup-only: true

  phylogenetic:
    # Run the workflow under two conditions
    # 1. `workflow_run` triggered `check-new-data` and there _is_ new data
    # 2. the workflow is being manually run by `workflow_dispatch`
    needs: [check-new-data]
    if: |
      always() &&
      (
        (needs.check-new-data.result == 'success' && needs.check-new-data.outputs.cache-hit != 'true') ||
        github.event_name == 'workflow_dispatch'
      )
    runs-on: ubuntu-latest
    steps:
      - run: echo "Mock phylogenetic"
