name: Test sparse checkout

on:
  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-latest
    env:
      ANALYSIS_EXAMPLE_DIR: configs/configs/
      ANALYSIS_DIR: analysis-directory/
    steps:
      - uses: actions/checkout@v7
        with:
          ref: ${{ github.sha }}
          sparse-checkout-cone-mode: false
          sparse-checkout: ${{ env.ANALYSIS_EXAMPLE_DIR }}
          path: ${{ env.ANALYSIS_DIR }}

      - run: ls -lah ${{ env.ANALYSIS_DIR}}${{ env.ANALYSIS_EXAMPLE_DIR }}*

      - run: mv ${{ env.ANALYSIS_DIR}}${{ env.ANALYSIS_EXAMPLE_DIR }}* ${{ env.ANALYSIS_DIR }}

      - run: ls -lah ${{ env.ANALYSIS_DIR }}*
