name: test

on:
  push:
    paths:
      - .github/workflows/test.yaml

  workflow_dispatch:
    inputs:
      boolean_input:
        description: Test boolean input
        type: boolean
        default: true
        required: false

env:
  EMPTY_STRING: ""
  NON_EMPTY_STRING: "hello"
  BOOLEAN_INPUT: ${{ inputs.boolean_input }}
  TEST_BOOLEAN: ${{ github.event_name != 'workflow_dispatch' && true || inputs.boolean_input }}

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      ref_matrix: ${{ steps.ref_matrix.outputs.ref_matrix }}
    steps:
      - if: null
        run: echo "Null truthy"

      - if: env.EMPTY_STRING
        run: echo "Empty string truthy"

      - if: env.EMPTY_STRING == ''
        run: echo "Compared empty string truthy"

      - if: env.NON_EMPTY_STRING != ''
        run: echo "Compared non empty string truthy"

      - run: |
          echo "boolean input: $BOOLEAN_INPUT"
          echo "test boolean: $TEST_BOOLEAN"

      - run: |
          echo "RESOURCE_INDEX=s3://nextstrain-inventories/resources/v1.json.gz" | tee -a "$GITHUB_ENV"

      - env:
          TEST: ${{ startsWith(env.RESOURCE_INDEX, 's3://') }}
        run:
          echo $TEST

      - id: ref_matrix
        run: |
          jq_filter='[ env.RESOURCE_INDEX ]'
          ref_matrix=$(jq -c --null-input "$jq_filter")
          echo "ref_matrix=$ref_matrix" | tee -a "$GITHUB_OUTPUT"


  test_matrix:
    needs: [test]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ref: ${{ fromJson(needs.test.outputs.ref_matrix) }}
    steps:
      - run: echo ${{ matrix.ref }}

  test_skipped:
    runs-on: ubuntu-latest
    if: |2
         github.repository == 'joverlee521/nextstrain-testing'
      && github.event_name == 'push'
      && github.ref == 'refs/heads/main'
    steps:
      - run: echo "NOT SKIPPED"

  test_depend_on_skipped:
    runs-on: ubuntu-latest
    needs:
      - test
      - test_skipped
    if: |2
         !cancelled()
      && needs.test.result == 'success'
      && contains(fromJSON('["success", "skipped"]'), needs.test_skipped.result)
      && github.repository == 'joverlee521/nextstrain-testing'
      && (   (github.event_name == 'push' && github.ref == 'refs/heads/main')
          || (github.event_name == 'workflow_dispatch' && inputs.boolean_input) )
    env:
      TEST_SKIPPED_RESULT: ${{ needs.test_skipped.result }}
      TEST_CONTAINS: ${{ contains(fromJSON('["success", "skipped"]'), needs.test_skipped.result)}}
    steps:
      - run: |
          echo "$TEST_SKIPPED_RESULT"
          echo "$TEST_CONTAINS"
