name: test

on: workflow_dispatch

env:
  NULL: null
  EMPTY_STRING: ""
  NON_EMPTY_STRING: "hello"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - if: null
        run: echo "Null truthy"

      - if: env.EMPTY_STRING
        run: echo "Empty string truthy"

      - if: env.EMPTY_STRING == ''
        run: echo "Compared empty string truthy"

      - if: env.NON_EMPTY_STRING != ''
        run: echo "Compared non empty string truthy"
