name: Test reusable

on:
  workflow_call:
    inputs:
      run:
        description: Command
        type: string

jobs:
  run_input:
    runs-on: ubuntu-latest
    steps:
      - name: Run input command
        run: |
          set -x

          ${{ inputs.run }} \
          |& tee build.log

      - uses: actions/upload-artifact@v3
        with:
          if-no-files-found: warn
          name: output
          path: |
            build.log
