name: Pathogen repo build

on: workflow_dispatch

jobs:
  run-build:
    # The `id-token: write` permission is required for this workflow.
    permissions:
      id-token: write
    uses: nextstrain/.github/.github/workflows/pathogen-repo-build.yaml@master
    with:
      repo: nextstrain/bogus-repo-that-will-fail

  notify-on-failure:
    needs: run-build
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nextstrain/.github/actions/notify-on-failure@notify-on-failure-action
        env:
          SLACK_CHANNELS: slack-test
          SLACK_TOKEN: bogus-slack-token
