name: Test RTD API

on:
  workflow_dispatch:

jobs:
  curl-rtd-api:
    runs-on: ubuntu-latest
    steps:
      - run: curl --verbose https://readthedocs.com/api/v3/

  python-rtd-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - run: python -m pip install certifi==2024.8.30
      - run: python bin/ping-rtd-api.py
