name: Reusable

on:
  workflow_call:
    inputs:
      ref:
        type: string
        required: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: joverlee521/nextstrain-testing
          ref: ${{ inputs.ref }}

      - run: ./bin/hello-world

      - run: ./bin/hello-new-world

      - name: local-fix
        run: |
          # Hack to get setup-python to work on act
          # (see https://github.com/nektos/act/issues/251)
          if [ ! -f "/etc/lsb-release" ] ; then
            echo "DISTRIB_RELEASE=18.04" > /etc/lsb-release
          fi

      - uses: nextstrain/.github/actions/setup-nextstrain-cli@master
        with:
          runtime: conda

      - name: Install envdir
        shell: nextstrain shell . {0}
        run: pip install envdir

      - name: Create env.d
        run: mkdir env.d

      - name: Add test envvar
        run: |
          cd env.d
          echo ${{ env.TEST }} > TEST
        env:
          TEST: HELLO-TEST

      - name: Run build
        run: |
          nextstrain build \
            --exec env . \
            envdir env.d printenv TEST

      - name: Check Augur
        shell: nextstrain shell . {0}
        run: augur --version
