name: Test hashfiles

on:
  workflow_dispatch:


jobs:

  check-new-data:
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.check-cache.outputs.cache-hit }}
    steps:
      - name: Get sha256sum
        id: get-sha256sum
        env:
          AWS_REGION: us-east-1
        run: |
          s3_urls=(
            "s3://nextstrain-data/files/workflows/zika/metadata.tsv.zst"
            "s3://nextstrain-data/files/workflows/zika/sequences.fasta.zst"
          )

          # Code below is modified from ingest/upload-to-s3
          # https://github.com/nextstrain/ingest/blob/c0b4c6bb5e6ccbba86374d2c09b42077768aac23/upload-to-s3#L23-L29

          no_hash=0000000000000000000000000000000000000000000000000000000000000000

          aws --version

          for s3_url in "${s3_urls[@]}"; do
            s3path="${s3_url#s3://}"
            bucket="${s3path%%/*}"
            key="${s3path#*/}"

            aws s3api head-object \
              --no-sign-request \
              --bucket "$bucket" \
              --key "$key" \
              --query Metadata.sha256sum \
              --output text \
              | tee -a ingest-output-sha256sum
          done

      - name: Check cache
        id: check-cache
        uses: actions/cache@v4
        with:
          path: ingest-output-sha256sum
          key: ingest-output-sha256sum-${{ hashFiles('ingest-output-sha256sum') }}
          lookup-only: true
