name: test

on:
  push:
    paths:
      - .github/workflows/test.yaml

  workflow_dispatch:
    inputs:
      boolean_input:
        description: Test boolean input
        type: boolean
        default: true
        required: false

env:
  EMPTY_STRING: ""
  NON_EMPTY_STRING: "hello"
  BOOLEAN_INPUT: ${{ inputs.boolean_input }}
  TEST_BOOLEAN: ${{ github.event_name != 'workflow_dispatch' && true || inputs.boolean_input }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - if: null
        run: echo "Null truthy"

      - if: env.EMPTY_STRING
        run: echo "Empty string truthy"

      - if: env.EMPTY_STRING == ''
        run: echo "Compared empty string truthy"

      - if: env.NON_EMPTY_STRING != ''
        run: echo "Compared non empty string truthy"

      - run: |
          echo "boolean input: $BOOLEAN_INPUT"
          echo "test boolean: $TEST_BOOLEAN"
