name: Reusable

on:
  workflow_call:
    inputs:
      ref:
        type: string
        required: true
      env:
        type: string
        required: false
      runtime-envvar-names:
        type: string
        required: false
      artifact-paths:
        type: string
        required: false

env:
  ENVDIR: env.d

jobs:
  configuration:
    runs-on: ubuntu-latest
    steps:
      - id: inputs
        env:
          paths: ${{ inputs.artifact-paths }}
        shell: bash
        run: |
          paths="$(yq --output-format=json --indent=0 . <<<"$paths")"
          echo paths="$paths" | tee -a "$GITHUB_OUTPUT"
    outputs:
      build-output-paths: ${{ steps.inputs.outputs.paths }}

  run:
    needs: configuration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: joverlee521/nextstrain-testing
          ref: ${{ inputs.ref }}

      - run: ./bin/hello-world

      - run: ./bin/hello-new-world

      - name: local-fix
        run: |
          # Hack to get setup-python to work on act
          # (see https://github.com/nektos/act/issues/251)
          if [ ! -f "/etc/lsb-release" ] ; then
            echo "DISTRIB_RELEASE=18.04" > /etc/lsb-release
          fi

      - uses: nextstrain/.github/actions/setup-nextstrain-cli@master
        with:
          runtime: conda

      - name: Install envdir
        shell: nextstrain shell . {0}
        run: pip install envdir

      - if: inputs.env
        name: Set environment variables
        env:
          env: ${{ inputs.env }}
        run: >
          echo "$env"
          | yq --output-format json .
          | ./bin/json-to-envvar
          | tee -a "$GITHUB_ENV"

      - name: Set secrets to envvars
        env:
          secrets: ${{ toJson(secrets) }}
        run: >
          echo "$secrets"
          | ./bin/json-to-envvar
          | tee -a "$GITHUB_ENV"

      - name: Add test envvar
        run: |
          ./bin/write-envdir ${{ env.ENVDIR }} ${{ inputs.runtime-envvar-names }}

      - name: Run build
        run: |
          nextstrain build \
            --exec env . \
            envdir ${{ env.ENVDIR }} printenv ${{ inputs.runtime-envvar-names }} \
          | tee build.log

      - name: Check Augur
        shell: nextstrain shell . {0}
        run: augur --version

      - if: always()
        uses: actions/upload-artifact@v3
        with:
          name: output
          path: |
            build.log
            ${{ needs.configuration.outputs.build-output-paths }}
            !${{ env.ENVDIR }}
