name: Test timeout in `run`

on: workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - id: sleep
        run: |
          exit_status=0
          timeout 55s sleep 5m || exit_status=$?
          if [[ $exit_status == 124 ]]; then
            echo "Command timed out"
            exit 0
          fi
          exit $exit_status
    outputs:
      sleep-step-conclusion: ${{ steps.sleep.conclusion }}
