name: Use reusable

on: workflow_dispatch

jobs:
  run-reusable:
    uses: joverlee521/nextstrain-testing/.github/workflows/test-reusable.yaml@main
    with:
      ref: main
      env: |
        NEXTSTRAIN_DOCKER_IMAGE: nextstrain/base:latest
        SLACK_TOKEN: secrets.BOGUS_SLACK_TOKEN
      runtime-envvar-names: SLACK_TOKEN
    secrets: inherit
