name: Use reusable

on: workflow_dispatch

jobs:
  run-reusable:
    uses: joverlee521/nextstrain-testing/.github/workflows/test-reusable.yaml@c0bf4b4a3679437047cff05fde596a4a218dbbee
    with:
      env: |
        NEXTSTRAIN_DOCKER_IMAGE: nextstrain/base:latest
      runtime-envvar-names: BOGUS_SLACK_TOKEN
      artifact-paths: |
        - env.d/
        - auspice/
    secrets: inherit
