name: Use reusable

on: workflow_dispatch

jobs:
  run-reusable:
    uses: joverlee521/nextstrain-testing/.github/workflows/test-reusable.yaml@main
    with:
      repo: nextstrain/zika-tutorial
      artifact-paths: |
        env.d/
        auspice/
        results/
        logs/
        .snakemake/log/
      env: |
        NEXTSTRAIN_DOCKER_IMAGE: BOGUS_IMAGE
        WHATEVER_ENV: WHATEVER_VALUE
    secrets:
      GITHUB_PAT: BOGUS_GITHUB_PAT
      SLACK_TOKEN: BOGUS_TOKEN
