name: Use reusable

on: workflow_dispatch

jobs:
  run-reusable-literal-keep:
      uses: joverlee521/nextstrain-testing/.github/workflows/test-reusable.yaml@main
      with:
        run: |+
          echo "run reusable literal keep"




  run-reusable-literal-clip:
    uses: joverlee521/nextstrain-testing/.github/workflows/test-reusable.yaml@main
    with:
      run: |
        echo "run reusable literal clip"

  run-reusable-literal-strip:
    uses: joverlee521/nextstrain-testing/.github/workflows/test-reusable.yaml@main
    with:
      run: |-
        echo "run reusable literal strip"

  run-reusable-folded-keep:
    uses: joverlee521/nextstrain-testing/.github/workflows/test-reusable.yaml@main
    with:
      run: |+
        echo "run reusable literal keep"




  run-reusable-folded-clip:
    uses: joverlee521/nextstrain-testing/.github/workflows/test-reusable.yaml@main
    with:
      run: >
        echo "run reusable folded clip"

  run-reusable-folded-strip:
    uses: joverlee521/nextstrain-testing/.github/workflows/test-reusable.yaml@main
    with:
      run: >-
        echo "run reusable folded"
