name: Use reusable

on: workflow_dispatch

jobs:
  run-reusable:
    uses: joverlee521/nextstrain-testing/.github/workflows/test-reusable.yaml@c820e7452a7893d19920c34d4606e93500deb70d
    with:
      env: |
        NEXTSTRAIN_DOCKER_IMAGE: nextstrain/base:latest
      runtime-envvar-names: BOGUS_SLACK_TOKEN
      artifact-paths: |
        - env.d/
        - auspice/
    secrets: inherit

  run-reusable-2:
    uses: joverlee521/nextstrain-testing/.github/workflows/test-reusable.yaml@d26d11292a6ae3e00031fb8c37ae71be53e6ac51
    with:
      env: |
        NEXTSTRAIN_DOCKER_IMAGE: nextstrain/base:latest
      runtime-envvar-names: BOGUS_SLACK_TOKEN
      artifact-paths: |
        - env.d/
        - auspice/
    secrets: inherit
